<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260409122000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add hippodrome referential table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE hippodrome (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_hippodrome_name ON hippodrome (name)');
        $this->addSql("INSERT INTO hippodrome (name) SELECT DISTINCT UPPER(TRIM(hippodrome)) FROM race WHERE TRIM(hippodrome) <> ''");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE hippodrome');
    }
}
