<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260409113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add horse/person alias tables for normalization';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE horse_alias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, horse_id INT NOT NULL, original_form VARCHAR(255) NOT NULL, canonical_form VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_horse_alias_canonical ON horse_alias (canonical_form)');
        $this->addSql('CREATE INDEX IDX_A7A56FEC76B275AD ON horse_alias (horse_id)');
        $this->addSql('CREATE TABLE person_alias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, person_id INT NOT NULL, original_form VARCHAR(255) NOT NULL, canonical_form VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_person_alias_canonical ON person_alias (canonical_form)');
        $this->addSql('CREATE INDEX IDX_93466D5A217BBB47 ON person_alias (person_id)');
        $this->addSql('ALTER TABLE horse_alias ADD CONSTRAINT FK_A7A56FEC76B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_alias ADD CONSTRAINT FK_93466D5A217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('INSERT INTO horse_alias (horse_id, original_form, canonical_form, created_at) SELECT id, name, UPPER(TRIM(name)), NOW() FROM horse');
        $this->addSql('INSERT INTO person_alias (person_id, original_form, canonical_form, created_at) SELECT id, name, UPPER(TRIM(name)), NOW() FROM person');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE horse_alias DROP CONSTRAINT FK_A7A56FEC76B275AD');
        $this->addSql('ALTER TABLE person_alias DROP CONSTRAINT FK_93466D5A217BBB47');
        $this->addSql('DROP TABLE horse_alias');
        $this->addSql('DROP TABLE person_alias');
    }
}
