<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409083928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE horse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sex VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_horse_name ON horse (name)');
        $this->addSql('CREATE TABLE participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, saddle_number INT DEFAULT NULL, finishing_position INT DEFAULT NULL, age_at_race INT DEFAULT NULL, distance_or_weight DOUBLE PRECISION DEFAULT NULL, shoeing_or_draw VARCHAR(50) DEFAULT NULL, performance_indicator VARCHAR(50) DEFAULT NULL, odds DOUBLE PRECISION DEFAULT NULL, music VARCHAR(255) DEFAULT NULL, career_earnings BIGINT DEFAULT NULL, race_id INT NOT NULL, horse_id INT NOT NULL, jockey_id INT DEFAULT NULL, trainer_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB55E24F20070F6B ON participation (jockey_id)');
        $this->addSql('CREATE INDEX IDX_AB55E24FFB08EDF6 ON participation (trainer_id)');
        $this->addSql('CREATE INDEX IDX_AB55E24F7E3C61F9 ON participation (owner_id)');
        $this->addSql('CREATE INDEX idx_participation_race ON participation (race_id)');
        $this->addSql('CREATE INDEX idx_participation_horse ON participation (horse_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_participation_race_horse ON participation (race_id, horse_id)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_person_name ON person (name)');
        $this->addSql('CREATE TABLE race (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, race_date DATE DEFAULT NULL, hippodrome VARCHAR(255) NOT NULL, meeting_number INT NOT NULL, race_number INT NOT NULL, discipline VARCHAR(20) DEFAULT NULL, source_date_code VARCHAR(30) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_race_identity ON race (race_date, hippodrome, meeting_number, race_number)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F6E59D40D FOREIGN KEY (race_id) REFERENCES race (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F76B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F20070F6B FOREIGN KEY (jockey_id) REFERENCES person (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES person (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES person (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F6E59D40D');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F76B275AD');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F20070F6B');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24FFB08EDF6');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F7E3C61F9');
        $this->addSql('DROP TABLE horse');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE race');
    }
}
