<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260409101500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add import session and import errors persistence';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE import_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) NOT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(30) NOT NULL, total_rows INT NOT NULL, rows_imported INT NOT NULL, rows_skipped INT NOT NULL, error_count INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE import_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id INT NOT NULL, row_number INT DEFAULT NULL, error_type VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL, error_message VARCHAR(1000) NOT NULL, source_snapshot JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5374B8D6613FECDF ON import_error (session_id)');
        $this->addSql('CREATE INDEX idx_import_error_row_number ON import_error (row_number)');
        $this->addSql('CREATE INDEX idx_import_session_imported_at ON import_session (imported_at)');
        $this->addSql('ALTER TABLE import_error ADD CONSTRAINT FK_5374B8D6613FECDF FOREIGN KEY (session_id) REFERENCES import_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE import_error DROP CONSTRAINT FK_5374B8D6613FECDF');
        $this->addSql('DROP TABLE import_error');
        $this->addSql('DROP TABLE import_session');
    }
}
