<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260409170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add pronostic snapshots, predictions and KPI metrics tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pronostic_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, race_id INT NOT NULL, snapshot_type VARCHAR(30) NOT NULL, comparison_status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, compared_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_entries INT NOT NULL, comparable_entries INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1940B6F6E59D40D2 ON pronostic_snapshot (race_id)');
        $this->addSql('CREATE INDEX idx_pronostic_snapshot_created ON pronostic_snapshot (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pronostic_snapshot_race_type ON pronostic_snapshot (race_id, snapshot_type)');
        $this->addSql('ALTER TABLE pronostic_snapshot ADD CONSTRAINT FK_1940B6F6E59D40D2 FOREIGN KEY (race_id) REFERENCES race (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE pronostic_prediction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, snapshot_id INT NOT NULL, participation_id INT NOT NULL, predicted_rank INT NOT NULL, predicted_score DOUBLE PRECISION NOT NULL, sub_scores JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CA5748924296D31F ON pronostic_prediction (snapshot_id)');
        $this->addSql('CREATE INDEX IDX_CA574892FDC8A3A3 ON pronostic_prediction (participation_id)');
        $this->addSql('CREATE INDEX idx_pronostic_prediction_snapshot_rank ON pronostic_prediction (snapshot_id, predicted_rank)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pronostic_prediction_snapshot_participation ON pronostic_prediction (snapshot_id, participation_id)');
        $this->addSql('ALTER TABLE pronostic_prediction ADD CONSTRAINT FK_CA5748924296D31F FOREIGN KEY (snapshot_id) REFERENCES pronostic_snapshot (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pronostic_prediction ADD CONSTRAINT FK_CA574892FDC8A3A3 FOREIGN KEY (participation_id) REFERENCES participation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE pronostic_metric (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, snapshot_id INT NOT NULL, metric_type VARCHAR(50) NOT NULL, metric_value DOUBLE PRECISION NOT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A4AA4D84296D31F ON pronostic_metric (snapshot_id)');
        $this->addSql('CREATE INDEX idx_pronostic_metric_type_calculated ON pronostic_metric (metric_type, calculated_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pronostic_metric_snapshot_type ON pronostic_metric (snapshot_id, metric_type)');
        $this->addSql('ALTER TABLE pronostic_metric ADD CONSTRAINT FK_7A4AA4D84296D31F FOREIGN KEY (snapshot_id) REFERENCES pronostic_snapshot (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pronostic_metric DROP CONSTRAINT FK_7A4AA4D84296D31F');
        $this->addSql('ALTER TABLE pronostic_prediction DROP CONSTRAINT FK_CA5748924296D31F');
        $this->addSql('ALTER TABLE pronostic_prediction DROP CONSTRAINT FK_CA574892FDC8A3A3');
        $this->addSql('ALTER TABLE pronostic_snapshot DROP CONSTRAINT FK_1940B6F6E59D40D2');

        $this->addSql('DROP TABLE pronostic_metric');
        $this->addSql('DROP TABLE pronostic_prediction');
        $this->addSql('DROP TABLE pronostic_snapshot');
    }
}
